# process .bashrc
if [ -f ~/.bashrc ]; then
        . ~/.bashrc
fi

# MacPorts Installer addition on 2010-06-19_at_19:50:30: adding an appropriate PATH variable for use with MacPorts.
export PATH=/opt/local/bin:/opt/local/sbin:$PATH
# Finished adapting your PATH environment variable for use with MacPorts.

